export const movies = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/3CxUndGhUcZdt1Zggjdb2HkLLQX.jpg",
      id: 640146,
      title: "Ant-Man and the Wasp: Quantumania",
      original_language: "en",
      original_title: "Ant-Man and the Wasp: Quantumania",
      overview:
        "Super-Hero partners Scott Lang and Hope van Dyne, along with with Hope's parents Janet van Dyne and Hank Pym, and Scott's daughter Cassie Lang, find themselves exploring the Quantum Realm, interacting with strange new creatures and embarking on an adventure that will push them beyond the limits of what they thought possible.",
      poster_path: "/ngl2FKBlU4fhbdsrtdom9LVLBXw.jpg",
      media_type: "movie",
      genre_ids: [28, 12, 878],
      popularity: 11938.691,
      release_date: "2023-02-15",
      video: false,
      vote_average: 6.54,
      vote_count: 2051,
    },
    {
      adult: false,
      backdrop_path: "/44immBwzhDVyjn87b3x3l9mlhAD.jpg",
      id: 934433,
      title: "Scream VI",
      original_language: "en",
      original_title: "Scream VI",
      overview:
        "Following the latest Ghostface killings, the four survivors leave Woodsboro behind and start a fresh chapter.",
      poster_path: "/wDWwtvkRRlgTiUr6TyLSMX8FCuZ.jpg",
      media_type: "movie",
      genre_ids: [27, 9648, 53],
      popularity: 3280.409,
      release_date: "2023-03-08",
      video: false,
      vote_average: 7.374,
      vote_count: 895,
    },
    {
      adult: false,
      backdrop_path: "/9n2tJBplPbgR2ca05hS5CKXwP2c.jpg",
      id: 502356,
      title: "The Super Mario Bros. Movie",
      original_language: "en",
      original_title: "The Super Mario Bros. Movie",
      overview:
        "While working underground to fix a water main, Brooklyn plumbers—and brothers—Mario and Luigi are transported down a mysterious pipe and wander into a magical new world. But when the brothers are separated, Mario embarks on an epic quest to find Luigi.",
      poster_path: "/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg",
      media_type: "movie",
      genre_ids: [16, 12, 10751, 14, 35],
      popularity: 8878.873,
      release_date: "2023-04-05",
      video: false,
      vote_average: 7.524,
      vote_count: 1626,
    },
    {
      adult: false,
      backdrop_path: "/8HfjrSxfTVKmjNh8cJjbu5eXzcX.jpg",
      id: 420808,
      title: "Peter Pan \u0026 Wendy",
      original_language: "en",
      original_title: "Peter Pan \u0026 Wendy",
      overview:
        "Wendy Darling, a young girl afraid to leave her childhood home behind, meets Peter Pan, a boy who refuses to grow up. Alongside her brothers and a tiny fairy, Tinker Bell, she travels with Peter to the magical world of Neverland. There, she encounters an evil pirate captain, Captain Hook, and embarks on a thrilling adventure that will change her life forever.",
      poster_path: "/9NXAlFEE7WDssbXSMgdacsUD58Y.jpg",
      media_type: "movie",
      genre_ids: [10751, 14, 28, 12],
      popularity: 222.764,
      release_date: "2023-04-20",
      video: false,
      vote_average: 5.988,
      vote_count: 162,
    },
    {
      adult: false,
      backdrop_path: "/b9UCfDzwiWw7mIFsIQR9ZJUeh7q.jpg",
      id: 868759,
      title: "Ghosted",
      original_language: "en",
      original_title: "Ghosted",
      overview:
        "Salt-of-the-earth Cole falls head over heels for enigmatic Sadie — but then makes the shocking discovery that she’s a secret agent. Before they can decide on a second date, Cole and Sadie are swept away on an international adventure to save the world.",
      poster_path: "/liLN69YgoovHVgmlHJ876PKi5Yi.jpg",
      media_type: "movie",
      genre_ids: [10749, 28, 35],
      popularity: 3333.596,
      release_date: "2023-04-18",
      video: false,
      vote_average: 7.279,
      vote_count: 502,
    },
    {
      adult: false,
      backdrop_path: "/8rpDcsfLJypbO6vREc0547VKqEv.jpg",
      id: 76600,
      title: "Avatar: The Way of Water",
      original_language: "en",
      original_title: "Avatar: The Way of Water",
      overview:
        "Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.",
      poster_path: "/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
      media_type: "movie",
      genre_ids: [878, 12, 28],
      popularity: 5065.316,
      release_date: "2022-12-14",
      video: false,
      vote_average: 7.7,
      vote_count: 7681,
    },
    {
      adult: false,
      backdrop_path: "/wybmSmviUXxlBmX44gtpow5Y9TB.jpg",
      id: 594767,
      title: "Shazam! Fury of the Gods",
      original_language: "en",
      original_title: "Shazam! Fury of the Gods",
      overview:
        'Billy Batson and his foster siblings, who transform into superheroes by saying "Shazam!", are forced to get back into action and fight the Daughters of Atlas, who they must stop from using a weapon that could destroy the world.',
      poster_path: "/2VK4d3mqqTc7LVZLnLPeRiPaJ71.jpg",
      media_type: "movie",
      genre_ids: [28, 35, 14],
      popularity: 6588.015,
      release_date: "2023-03-15",
      video: false,
      vote_average: 6.8,
      vote_count: 1364,
    },
    {
      adult: false,
      backdrop_path: "/7bWxAsNPv9CXHOhZbJVlj2KxgfP.jpg",
      id: 713704,
      title: "Evil Dead Rise",
      original_language: "en",
      original_title: "Evil Dead Rise",
      overview:
        "Two sisters find an ancient vinyl that gives birth to bloodthirsty demons that run amok in a Los Angeles apartment building and thrusts them into a primal battle for survival as they face the most nightmarish version of family imaginable.",
      poster_path: "/mIBCtPvKZQlxubxKMeViO2UrP3q.jpg",
      media_type: "movie",
      genre_ids: [27, 53],
      popularity: 2221.987,
      release_date: "2023-04-12",
      video: false,
      vote_average: 7.025,
      vote_count: 296,
    },
    {
      adult: false,
      backdrop_path: "/3cgRI0hOq3dYyezSYrsfdmqxtMw.jpg",
      id: 114922,
      name: "Citadel",
      original_language: "en",
      original_name: "Citadel",
      overview:
        "What if you lost your memory? What if a spy didn’t know they were a spy? Years ago, the top agents of Citadel, Mason Kane and Nadia Sinh, had their minds wiped. But, they’re called back to action as sinister forces emerge from the past. With the help of spymaster Bernard Orlick, these former lovers must remember the past to save the future.",
      poster_path: "/AcrDB32TqpAGwvQFbICALGxSzn3.jpg",
      media_type: "tv",
      genre_ids: [18, 80, 10759],
      popularity: 421.67,
      first_air_date: "2023-04-27",
      vote_average: 8.2,
      vote_count: 42,
      origin_country: ["US"],
    },
    {
      adult: false,
      backdrop_path: "/6Lw54zxm6BAEKJeGlabyzzR5Juu.jpg",
      id: 82856,
      name: "The Mandalorian",
      original_language: "en",
      original_name: "The Mandalorian",
      overview:
        "After the fall of the Galactic Empire, lawlessness has spread throughout the galaxy. A lone gunfighter makes his way through the outer reaches, earning his keep as a bounty hunter.",
      poster_path: "/eU1i6eHXlzMOlEq0ku1Rzq7Y4wA.jpg",
      media_type: "tv",
      genre_ids: [10765, 10759, 18],
      popularity: 878.853,
      first_air_date: "2019-11-12",
      vote_average: 8.5,
      vote_count: 8935,
      origin_country: ["US"],
    },
    {
      adult: false,
      backdrop_path: "/h8gHn0OzBoaefsYseUByqsmEDMY.jpg",
      id: 603692,
      title: "John Wick: Chapter 4",
      original_language: "en",
      original_title: "John Wick: Chapter 4",
      overview:
        "With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.",
      poster_path: "/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg",
      media_type: "movie",
      genre_ids: [28, 53, 80],
      popularity: 1952.823,
      release_date: "2023-03-22",
      video: false,
      vote_average: 7.951,
      vote_count: 1264,
    },
    {
      adult: false,
      backdrop_path: "/nTvM4mhqNlHIvUkI1gVnW6XP7GG.jpg",
      id: 85937,
      name: "Demon Slayer: Kimetsu no Yaiba",
      original_language: "ja",
      original_name: "鬼滅の刃",
      overview:
        "It is the Taisho Period in Japan. Tanjiro, a kindhearted boy who sells charcoal for a living, finds his family slaughtered by a demon. To make matters worse, his younger sister Nezuko, the sole survivor, has been transformed into a demon herself. Though devastated by this grim reality, Tanjiro resolves to become a “demon slayer” so that he can turn his sister back into a human, and kill the demon that massacred his family.",
      poster_path: "/xUfRZu2mi8jH6SzQEJGP6tjBuYj.jpg",
      media_type: "tv",
      genre_ids: [16, 10759, 10765],
      popularity: 445.136,
      first_air_date: "2019-04-06",
      vote_average: 8.699,
      vote_count: 5113,
      origin_country: ["JP"],
    },
    {
      adult: false,
      backdrop_path: "/eEF40Xk2twM3WjRNZftfo771gjv.jpg",
      id: 700391,
      title: "65",
      original_language: "en",
      original_title: "65",
      overview:
        "65 million years ago, the only 2 survivors of a spaceship from Somaris that crash-landed on Earth must fend off dinosaurs and reach the escape vessel in time before an imminent asteroid strike threatens to destroy the planet.",
      poster_path: "/rzRb63TldOKdKydCvWJM8B6EkPM.jpg",
      media_type: "movie",
      genre_ids: [878, 12, 53, 28],
      popularity: 1665.196,
      release_date: "2023-03-02",
      video: false,
      vote_average: 6.277,
      vote_count: 861,
    },
    {
      adult: false,
      backdrop_path: "/dQObIWkxfzKEDhtjOSoFnyCVgt0.jpg",
      id: 447365,
      title: "Guardians of the Galaxy Volume 3",
      original_language: "en",
      original_title: "Guardians of the Galaxy Volume 3",
      overview:
        "Peter Quill, still reeling from the loss of Gamora, must rally his team around him to defend the universe along with protecting one of their own. A mission that, if not completed successfully, could quite possibly lead to the end of the Guardians as we know them.",
      poster_path: "/y0G2ybLpVwIxYaPLT1qkn8J5o44.jpg",
      media_type: "movie",
      genre_ids: [878, 12, 28],
      popularity: 462.751,
      release_date: "2023-05-03",
      video: false,
      vote_average: 8.4,
      vote_count: 13,
    },
    {
      adult: false,
      backdrop_path: "/zh614Bixv2ePaHK8gzcUpUmcvYv.jpg",
      id: 1102776,
      title: "AKA",
      original_language: "fr",
      original_title: "AKA",
      overview:
        "A steely special ops agent finds his morality put to the test when he infiltrates a crime syndicate and unexpectedly bonds with the boss' young son.",
      poster_path: "/3BSxAjiporlwQTWzaHZ9Yrl5C9D.jpg",
      media_type: "movie",
      genre_ids: [53, 28, 80],
      popularity: 131.26,
      release_date: "2023-04-28",
      video: false,
      vote_average: 6.8,
      vote_count: 64,
    },
    {
      adult: false,
      backdrop_path: "/xwA90BwZXTh8ke3CVsQlj8EOkFr.jpg",
      id: 948713,
      title: "The Last Kingdom: Seven Kings Must Die",
      original_language: "en",
      original_title: "The Last Kingdom: Seven Kings Must Die",
      overview:
        "In the wake of King Edward's death, Uhtred of Bebbanburg and his comrades adventure across a fractured kingdom in the hopes of uniting England at last.",
      poster_path: "/7yyFEsuaLGTPul5UkHc5BhXnQ0k.jpg",
      media_type: "movie",
      genre_ids: [28, 12, 36, 18, 10752],
      popularity: 4271.498,
      release_date: "2023-04-14",
      video: false,
      vote_average: 7.31,
      vote_count: 274,
    },
    {
      adult: false,
      backdrop_path: "/7TdVWAO7vV9j1OLDq1hQJS3pb4U.jpg",
      id: 739405,
      title: "Operation Fortune: Ruse de Guerre",
      original_language: "en",
      original_title: "Operation Fortune: Ruse de Guerre",
      overview:
        "Special agent Orson Fortune and his team of operatives recruit one of Hollywood's biggest movie stars to help them on an undercover mission when the sale of a deadly new weapons technology threatens to disrupt the world order.",
      poster_path: "/uo7vWfQUlVwueYTDRicXOJa8Oow.jpg",
      media_type: "movie",
      genre_ids: [28, 35, 12],
      popularity: 165.939,
      release_date: "2023-01-04",
      video: false,
      vote_average: 6.66,
      vote_count: 616,
    },
    {
      adult: false,
      backdrop_path: "/vYm3JDA5ZZbs9hvLs0mPQzqaY95.jpg",
      id: 103768,
      name: "Sweet Tooth",
      original_language: "en",
      original_name: "Sweet Tooth",
      overview:
        "On a perilous adventure across a post-apocalyptic world, a lovable boy who's half-human and half-deer searches for a new beginning with a gruff protector.",
      poster_path: "/dBxxtfhC4vYrxB2fLsSxOTY2dQc.jpg",
      media_type: "tv",
      genre_ids: [18, 10765],
      popularity: 463.271,
      first_air_date: "2021-06-04",
      vote_average: 7.931,
      vote_count: 1117,
      origin_country: ["US"],
    },
    {
      adult: false,
      backdrop_path: "/5i6SjyDbDWqyun8klUuCxrlFbyw.jpg",
      id: 677179,
      title: "Creed III",
      original_language: "en",
      original_title: "Creed III",
      overview:
        "After dominating the boxing world, Adonis Creed has been thriving in both his career and family life. When a childhood friend and former boxing prodigy, Damian Anderson, resurfaces after serving a long sentence in prison, he is eager to prove that he deserves his shot in the ring. The face-off between former friends is more than just a fight. To settle the score, Adonis must put his future on the line to battle Damian — a fighter who has nothing to lose.",
      poster_path: "/cvsXj3I9Q2iyyIo95AecSd1tad7.jpg",
      media_type: "movie",
      genre_ids: [18, 28],
      popularity: 3900.913,
      release_date: "2023-03-01",
      video: false,
      vote_average: 7.3,
      vote_count: 1240,
    },
    {
      adult: false,
      backdrop_path: "/pGtvfzfIRCsiudAWlzlGZ74co5l.jpg",
      id: 124800,
      name: "Love \u0026 Death",
      original_language: "en",
      original_name: "Love \u0026 Death",
      overview:
        "The true story of Candy and Pat Montgomery and Betty and Allan Gore – two churchgoing couples enjoying their small town Texas life… until an extramarital affair leads somebody to pick up an axe.",
      poster_path: "/8WchbT0UPQeo3PZ6G01fhccYaQB.jpg",
      media_type: "tv",
      genre_ids: [80, 18],
      popularity: 207.239,
      first_air_date: "2023-04-27",
      vote_average: 8.2,
      vote_count: 30,
      origin_country: ["US"],
    },
  ],
  total_pages: 1000,
  total_results: 20000,
};
